const modal=document.getElementById('modal'),content=document.getElementById('toolContent');
function openTool(name){modal.classList.remove('hidden');const tools={
attendance:`<h2 class="tool-title">📊 Attendance Calculator</h2><p>Enter attended and total classes.</p><div class="form-grid"><div class="field"><label>Attended</label><input id="att" type="number" min="0"></div><div class="field"><label>Total classes</label><input id="tot" type="number" min="1"></div><div class="field"><label>Target %</label><input id="target" type="number" value="75"></div></div><button class="btn" onclick="calcAttendance()">Calculate</button><div id="out" class="result" style="display:none"></div>`,
cgpa:`<h2 class="tool-title">🎓 CGPA Calculator</h2><p>Enter each subject's credit and grade point.</p><div id="subjects"></div><button class="btn" onclick="addSubject()">+ Add subject</button> <button class="btn" onclick="calcCGPA()">Calculate</button><div id="out" class="result" style="display:none"></div>`,
planner:`<h2 class="tool-title">📅 Study Planner</h2><p>Build a quick plan from your available study hours.</p><div class="form-grid"><div class="field"><label>Hours available</label><input id="hours" type="number" value="4" min="1"></div><div class="field"><label>Subjects</label><input id="subs" placeholder="Math, Biology, Physics"></div></div><button class="btn" onclick="makePlan()">Create plan</button><div id="out" class="result" style="display:none"></div>`,
budget:`<h2 class="tool-title">💰 Student Budget</h2><div class="form-grid"><div class="field"><label>Monthly income (₹)</label><input id="income" type="number"></div><div class="field"><label>Food</label><input id="food" type="number"></div><div class="field"><label>Travel</label><input id="travel" type="number"></div><div class="field"><label>Other</label><input id="other" type="number"></div></div><button class="btn" onclick="calcBudget()">Calculate</button><div id="out" class="result" style="display:none"></div>`,
resume:`<h2 class="tool-title">📄 Resume Builder</h2><div class="form-grid"><div class="field"><label>Name</label><input id="rname"></div><div class="field"><label>Email</label><input id="remail"></div><div class="field full"><label>Skills</label><input id="skills" placeholder="Python, Excel, Communication"></div><div class="field full"><label>Education</label><textarea id="edu" rows="3"></textarea></div></div><button class="btn" onclick="makeResume()">Generate preview</button><div id="out" class="result" style="display:none"></div>`};
content.innerHTML=tools[name];if(name==='cgpa'){addSubject();addSubject();}}
function closeTool(){modal.classList.add('hidden')}function closeIfBackdrop(e){if(e.target===modal)closeTool()}
function calcAttendance(){let a=+document.getElementById('att').value,t=+document.getElementById('tot').value,tr=+document.getElementById('target').value;if(!t||a>t||a<0||tr<0||tr>=100)return show('Enter valid numbers (target must be below 100%).');let pct=a/t*100;let need=Math.max(0,Math.ceil((tr*t-a)/(1-tr/100)));show(`Current attendance: ${pct.toFixed(1)}%. ${need?`You need about ${need} consecutive attended classes to reach ${tr}%.`:`You are already at/above ${tr}%.`}`)}
function addSubject(){let d=document.createElement('div');d.className='form-grid';d.innerHTML='<div class="field"><label>Credit</label><input class="credit" type="number" min="1" value="3"></div><div class="field"><label>Grade point</label><input class="grade" type="number" min="0" max="10" value="8"></div>';document.getElementById('subjects').appendChild(d)}
function calcCGPA(){let cs=[...document.querySelectorAll('.credit')],gs=[...document.querySelectorAll('.grade')],tc=0,tp=0;for(let i=0;i<cs.length;i++){let c=+cs[i].value,g=+gs[i].value;if(c<=0||g<0||g>10)return show('Enter valid credits and grade points (0–10).');tc+=c;tp+=c*g}show(tc?`Your CGPA is ${(tp/tc).toFixed(2)}`:'Add at least one subject.')}
function makePlan(){let h=+document.getElementById('hours').value,s=document.getElementById('subs').value.split(',').map(x=>x.trim()).filter(Boolean);if(!s.length||h<=0)return show('Enter available hours and at least one subject.');let mins=Math.floor(h*60/s.length);show(s.map((x,i)=>`${i+1}. ${x}: ${mins} minutes`).join('<br>'))}
function calcBudget(){let income=+document.getElementById('income').value;let expenses=['food','travel','other'].reduce((sum,id)=>sum+(+document.getElementById(id).value||0),0);if(income<0||expenses<0)return show('Enter valid amounts.');let left=income-expenses;show(`Money remaining: ₹${left.toLocaleString('en-IN')}`)}
function makeResume(){let esc=s=>s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));let name=esc(document.getElementById('rname').value||'Your Name'),email=esc(document.getElementById('remail').value||''),skills=esc(document.getElementById('skills').value||'Add your skills'),edu=esc(document.getElementById('edu').value||'Add your education').replace(/\n/g,'<br>');show(`<strong>${name}</strong><br>${email}<br><br><b>Skills</b><br>${skills}<br><br><b>Education</b><br>${edu}`)}
function show(t){let o=document.getElementById('out');o.style.display='block';o.innerHTML=t}